# Generated by Django 5.0.6 on 2024-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_alter_musicianmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='musicianmodel',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
