# Generated by Django 5.0.6 on 2024-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_remove_musicianmodel_id_musicianmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
