# Generated by Django 5.0.6 on 2024-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('binaryfield', models.BinaryField()),
                ('Check', models.BooleanField()),
                ('feedback', models.CharField(max_length=255)),
            ],
        ),
    ]
