# Generated by Django 5.0.6 on 2024-06-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.TextField(),
        ),
    ]
