# Generated by Django 5.0.6 on 2024-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_task_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateField(),
        ),
    ]
