# Generated by Django 5.0.7 on 2024-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands_image_logo/'),
        ),
    ]
