# Generated by Django 5.0.7 on 2024-07-13 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image1', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('car_image2', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('car_image3', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('car_name', models.CharField(max_length=250)),
                ('car_type', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=5)),
                ('car_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=30)),
                ('car_price', models.IntegerField()),
                ('car_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('car_mileage', models.IntegerField()),
                ('car_location', models.CharField(max_length=150)),
                ('car_description', models.TextField()),
                ('car_body_style', models.CharField(max_length=150)),
                ('car_drive_type', models.CharField(max_length=150)),
                ('car_stock_id', models.IntegerField()),
                ('car_vin', models.CharField(max_length=100)),
                ('car_users', models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cars.carmodel')),
            ],
        ),
    ]
