# Generated by Django 5.0.7 on 2024-07-13 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
