# Generated by Django 5.0.7 on 2024-07-13 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandmodel_brand_image'),
        ('cars', '0002_alter_carmodel_car_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_users',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brandmodel'),
        ),
    ]
