# Generated by Django 5.0.7 on 2024-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_car_users_carmodel_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_fuel_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
