# Generated by Django 5.0.6 on 2024-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='album_rating',
            field=models.ImageField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], upload_to=''),
        ),
    ]
