# Generated by Django 5.0.6 on 2024-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_albummodel_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='album_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
